---
# tasks file for init-vm

- name: setup keyboard
  include_tasks: keyboards.yml

- name: setup Alpine vm
  include_tasks: setup_gui_alpine.yml
  when: ansible_distribution is search("Alpine")

- name: change grub config
  include_tasks: grub.yml
